/* WarpTris - run time language support (see standardization plan, section 8) */

#ifndef LANG_H
#define LANG_H

#define LANG_EN  0
#define LANG_ES  1
#define LANG_NL  2
#define LANG_DE  3
#define LANG_FR  4
#define LANG_IT  5
#define LANG_COUNT 6

enum {
    STR_MENU_GAME = 0, STR_MENU_NEW, STR_MENU_PAUSE, STR_MENU_QUIT, STR_MENU_EXIT,
    STR_MENU_IMPULSE, STR_MENU_DONKEY, STR_MENU_FORMULA1, STR_MENU_WARP,
    STR_MENU_SOUND, STR_MENU_SOUNDON, STR_MENU_SOUNDOFF,
    STR_MENU_OPTIONS, STR_MENU_PROPERTIES, STR_MENU_DETAIL,
    STR_MENU_DET_HIGH, STR_MENU_DET_MEDIUM, STR_MENU_DET_LOW,
    STR_MENU_LANGUAGE, STR_MENU_BACKGRND, STR_MENU_FRAME, STR_MENU_SAVEONEXIT,
    STR_MENU_WINDOWS, STR_MENU_HIGHWIN, STR_MENU_NEXTWIN, STR_MENU_SCOREWIN,
    STR_MENU_GAMEWIN, STR_MENU_ARRANGE,
    STR_MENU_HELP, STR_MENU_GENHELP, STR_MENU_HELPINDEX, STR_MENU_HELPONHELP,
    STR_MENU_ABOUT,
    /* --- window titles --- */
    STR_WIN_GAME, STR_WIN_SCORE, STR_WIN_NEXT, STR_WIN_HIGH, STR_WIN_PROPS,
    STR_WIN_PAUSED, STR_HELP_TITLE, STR_PAGE_OF,
    /* --- properties notebook --- */
    STR_TAB_SOUND, STR_TAB_WINDOWS, STR_TAB_IMPULSE,
    STR_ON, STR_OFF, STR_ENABLED_WINDOWS,
    /* --- dialogs --- */
    STR_EXIT_TITLE, STR_EXIT_TEXT, STR_YES, STR_NO,
    STR_OVER_TITLE, STR_OK, STR_NEW,
    STR_NAME_TITLE, STR_NAME_TEXT, STR_NAME_GROUP, STR_ENTER,
    STR_ANON, STR_HELP_MISSING,
    STR_COUNT
};

extern int current_lang;
extern const char *lang_strings[LANG_COUNT][STR_COUNT];
#define tr(id) ((char *)lang_strings[current_lang][(id)])

#endif /* LANG_H */
